import { icon } from '../components/icons.mjs';
import { cta } from '../components/sections.mjs';
export function about() {
  return `<div class="about-page">
<section class="container editorial-section"><div><p class="eyebrow">O QUE NOS MOVE</p><h1>O objetivo dá<br>direção ao trabalho.</h1><p class="about-lead">Uma presença digital precisa fazer sentido para a marca e para quem está do outro lado.</p></div><div class="editorial-copy"><p>A JG Agência trabalha com tráfego pago, social media, sites e landing pages. Cada solução tem um papel diferente, mas todas precisam partir da mesma pergunta: o que o seu negócio quer alcançar?</p><p>A proposta é entender a empresa, sua oferta e seu público antes de escolher ferramentas ou campanhas. Assim, comunicação, investimento em mídia e presença digital podem seguir uma direção clara.</p><p>Isso significa olhar para a jornada completa: como as pessoas descobrem sua marca, o que encontram ao conhecê-la e como podem dar o próximo passo. O projeto deve conectar essas etapas, com uma mensagem consistente e uma experiência simples.</p></div></section>
<section class="soft-section"><div class="container"><p class="eyebrow">NOSSA PROPOSTA</p><h2 class="about-section-title">Clareza em cada etapa.<br>Propósito em cada escolha.</h2><p class="about-section-description">Do primeiro contato à evolução do projeto, o trabalho parte das necessidades do negócio e de prioridades bem definidas.</p><div class="principle-list"><article><span class="service-number">01</span><h2>Entender</h2><p>Conhecer sua oferta, seu público e seus objetivos. Identificar o momento da empresa, os desafios da comunicação e as oportunidades que merecem atenção.</p></article><article><span class="service-number">02</span><h2>Planejar</h2><p>Definir prioridades, canais e entregas. Escolher as soluções que fazem sentido para o projeto e alinhar o escopo antes de começar a execução.</p></article><article><span class="service-number">03</span><h2>Construir</h2><p>Transformar a estratégia em conteúdo, campanhas e experiências digitais. Combinar identidade visual, mensagem e funcionalidade para uma presença coerente.</p></article><article><span class="service-number">04</span><h2>Acompanhar</h2><p>Revisar as entregas e observar os resultados disponíveis. Usar o aprendizado para orientar ajustes e os próximos passos, conforme o serviço contratado.</p></article></div></div></section>

<section class="soft-section"><div class="container about-partnership"><div><p class="eyebrow">PARCERIA NO DIA A DIA</p><h2 class="about-section-title">Você entende o caminho.<br>A gente constrói junto.</h2><p class="about-section-description">Um projeto bem alinhado começa com uma conversa clara e continua com participação, organização e atenção às necessidades da sua empresa.</p></div><div class="about-partnership-list"><article>${icon('target')}<div><h3>Estratégia personalizada</h3><p>O ponto de partida é a realidade do seu negócio. Objetivos, público e prioridades orientam as decisões do projeto.</p></div></article><article>${icon('chat')}<div><h3>Comunicação transparente</h3><p>Escopo e etapas alinhados para que você saiba o que está sendo desenvolvido e possa contribuir nas decisões.</p></div></article><article>${icon('chart')}<div><h3>Foco no que faz sentido</h3><p>Escolhas de conteúdo, design e tecnologia conectadas à experiência do público e ao objetivo de cada entrega.</p></div></article></div></div></section>${cta()}</div>`;
}
