import { services } from '../data/site.mjs';
import { icon } from '../components/icons.mjs';
import { contactForm } from '../components/contact-form.mjs';
import { projectImage } from '../components/sections.mjs';
const serviceIcons = ['chart', 'social', 'monitor', 'page'];
const steps = [
  ['search', 'Entendemos seu negócio', 'Conhecemos seus objetivos, seu público e o momento da empresa.'],
  ['target', 'Definimos a estratégia', 'Escolhemos as soluções que fazem sentido para o seu objetivo.'],
  ['rocket', 'Executamos o projeto', 'Colocamos a estratégia em prática com clareza e cuidado.'],
  ['chart', 'Acompanhamos e ajustamos', 'Revisamos o trabalho e os próximos passos conforme o escopo.']
];
const differences = [
  ['target', 'Estratégia personalizada', 'Planejamento de acordo com a realidade do seu negócio.'],
  ['chat', 'Comunicação transparente', 'Clareza sobre as etapas e as decisões do projeto.'],
  ['chart', 'Foco em oportunidades', 'Ações pensadas para aproximar sua empresa do público certo.'],
  ['people', 'Parceria próxima', 'Uma conversa que conecta seu objetivo ao trabalho realizado.']
];
export function home() {
  return `<section class="photo-hero"><img class="hero-photo" src="/assets/hero-laptop.jpg" alt="" width="1672" height="941" fetchpriority="high"><div class="container photo-hero-inner"><div class="hero-copy"><h1>Marketing digital<br>para negócios que<br>querem <em>crescer.</em></h1><p class="hero-description">Estratégia em tráfego pago, social media e desenvolvimento de sites para transformar presença digital em oportunidades reais.</p><div class="hero-actions"><a class="button" href="#fale-com-a-jg">Fale com a gente</a><a class="button button-outline" href="/servicos/">Conheça nossos serviços</a></div><div class="hero-values"><span>${icon('shield')}Estratégia real</span><span>${icon('chart')}Foco em oportunidades</span><span>${icon('people')}Parceria próxima</span></div></div></div></section>
  <section class="home-services"><div class="container"><div class="home-section-heading"><div><p class="eyebrow">NOSSOS SERVIÇOS</p><h2>Soluções completas<br>para o seu crescimento.</h2></div><div class="heading-aside"><p>Unimos estratégia, criatividade e tecnologia para transformar presença digital em oportunidades reais.</p><a class="text-link" href="/servicos/">Conheça todos os serviços</a></div></div><div class="service-cards">${services.map((s, i) => `<article class="service-card"><span class="icon-box">${icon(serviceIcons[i])}</span><h3>${s.name}</h3><p>${s.description}</p><a class="text-link" href="/servicos/${s.slug}/">Saiba mais<span class="sr-only"> sobre ${s.name}</span></a></article>`).join('')}</div></div></section>
  <section class="home-about"><div class="about-story"><p class="eyebrow">SOBRE A JG</p><h2>Estratégia<br>antes de execução.</h2><p>Todo negócio tem seu próprio momento. Nosso trabalho começa com a compreensão dos seus objetivos e do seu público, para definir uma direção clara e escolher as ferramentas certas.</p><div class="about-values"><span>${icon('plan')}Planejamento<br>e estratégia</span><span>${icon('target')}Execução<br>com foco</span><span>${icon('chart')}Acompanhamento<br>e ajustes</span></div><a class="button" href="/sobre/">Conheça mais sobre a JG</a></div><img class="about-photo" src="/assets/office-desk.jpg" alt="Imagem ilustrativa de uma mesa com notebook, caderno e caneca JG." width="1448" height="1086" loading="lazy"></section>
  <section class="home-case"><div class="container case-feature"><div><p class="eyebrow">CASE EM DESTAQUE</p><h2>Fábio Lima Noivos</h2><p class="case-service">Desenvolvimento de Site</p><p class="case-description">Projeto de desenvolvimento de site. A apresentação completa do trabalho será adicionada com as informações e imagens reais do projeto.</p><a class="button" href="/projetos/fabio-lima-noivos/">Ver case completo</a></div><div class="case-preview">${projectImage()}</div></div></section>
  <section class="home-process"><div class="container"><div class="home-section-heading"><div><p class="eyebrow">COMO TRABALHAMOS</p><h2>Do planejamento<br>à execução.</h2></div><div class="heading-aside"><p>Um processo simples e estratégico para manter cada etapa alinhada ao seu objetivo.</p></div></div><div class="process-steps">${steps.map(([symbol, title, description], i) => `<article><span class="step-number">0${i + 1}</span><div class="step-title">${icon(symbol)}<h3>${title}</h3></div><p>${description}</p></article>`).join('')}</div></div></section>
  <section class="home-differences"><div class="container differences-layout"><div><p class="eyebrow">POR QUE ESCOLHER A JG</p><h2>Mais do que serviços,<br>parceria para o seu crescimento.</h2></div><div class="differences-grid">${differences.map(([symbol, title, description]) => `<article><span class="icon-box">${icon(symbol)}</span><div><h3>${title}</h3><p>${description}</p></div></article>`).join('')}</div></div></section>
  <section class="home-contact" id="fale-com-a-jg"><div class="container home-contact-grid"><div class="home-contact-copy"><p class="eyebrow">FALE COM A GENTE</p><h2>Pronto para dar<br>o próximo passo?</h2><p>Converse com a JG e descubra como podemos ajudar o seu negócio a crescer no digital.</p><div class="contact-values"><span>${icon('chat')}Conversa<br>personalizada</span><span>${icon('bolt')}Direção<br>para o projeto</span><span>${icon('shield')}Objetivos<br>em primeiro lugar</span></div></div><div class="home-form contact-form-area">${contactForm()}</div></div></section>`;
}
