import { projects } from '../data/site.mjs';
import { intro, cta, projectImage } from '../components/sections.mjs';
export function projectsPage() {
  return `${intro('PROJETOS', 'Estratégia que<br><em>ganha forma.</em>', 'Um espaço para apresentar o trabalho desenvolvido pela JG. Cada projeto tem seu contexto e seu objetivo.', 'office-desk.jpg')}<section class="container portfolio" aria-label="Portfólio">${projects.map(p => `<article>${projectImage()}<div class="project-info"><div><p class="eyebrow">${p.service.toUpperCase()}</p><h2>${p.name}</h2></div><p>${p.description}</p><a class="text-link" href="/projetos/${p.slug}/">Ver case completo</a></div></article>`).join('')}</section>${cta()}`;
}
export function casePage() {
  const p = projects[0];
  return `${intro('PROJETOS / DESENVOLVIMENTO DE SITE', p.name, 'Desenvolvimento de Site')}<section class="container case-visual">${projectImage()}<p class="asset-note">Imagem do projeto pendente de fornecimento.</p></section><section class="container case-content"><div><p class="eyebrow">SOBRE O PROJETO</p><h2>O trabalho,<br>em detalhes.</h2></div><div class="case-chapters"><article><h3>Contexto</h3><p class="content-pending">Conteúdo pendente: contexto do cliente e necessidade inicial aguardam informações reais.</p></article><article><h3>Objetivo do projeto</h3><p class="content-pending">Conteúdo pendente: objetivo e requisitos do site serão apresentados após confirmação.</p></article><article><h3>O que a JG desenvolveu</h3><p>Serviço informado: desenvolvimento de site para Fábio Lima Noivos.</p><p class="content-pending">Conteúdo pendente: páginas, funcionalidades e escopo do trabalho aguardam confirmação.</p></article><article><h3>Imagens do projeto</h3><p class="content-pending">Conteúdo pendente: capturas reais das versões desktop e mobile ainda não fornecidas.</p></article></div></section><div class="container case-back"><a class="text-link" href="/projetos/">Voltar aos projetos</a></div>${cta('Vamos construir a presença<br>digital do seu negócio?')}`;
}
