import { services } from '../data/site.mjs';
import { servicePages } from '../data/service-pages.mjs';
import { intro, projectImage } from '../components/sections.mjs';
import { icon } from '../components/icons.mjs';
import { serviceHero, includedSection, processSection, audienceSection, serviceFinal } from '../components/service-sections.mjs';
export function servicesPage() {
  const steps = [['Entender','Mergulhamos no seu negócio, público e objetivos para identificar as melhores oportunidades.'],['Planejar','Desenhamos a estratégia com um plano de ação claro e conectado ao seu objetivo.'],['Executar','Colocamos o plano em prática, com atenção aos detalhes e à experiência do público.'],['Acompanhar','Observamos os resultados disponíveis e orientamos os próximos ajustes.']];
  return `<div class="services-hub"><section class="hub-hero"><div class="container hub-hero-grid"><div><p class="eyebrow">NOSSOS SERVIÇOS</p><h1>Soluções para marcas<br>que querem crescer<br>com direção.</h1><p class="hub-lead">Tráfego pago, social media, sites e landing pages.<br>Estratégia, criatividade e execução para o seu negócio conquistar mais oportunidades no digital.</p><div class="hub-actions"><a class="button button-light" href="/contato/">Fale com a gente →</a><a class="button hub-outline" href="#nossa-abordagem">Conheça nossa abordagem</a></div></div><aside><p>Mais do que serviços isolados, pensamos em soluções alinhadas aos objetivos da sua marca. Cada estratégia parte do seu momento, com foco em uma presença digital consistente.</p><span>ESTRATÉGIA<br>QUE GERA MOVIMENTO</span></aside></div></section>
<section class="container hub-services"><div class="hub-section-heading"><div><p class="eyebrow">NOSSOS SERVIÇOS</p><h2>Estratégia e execução para<br>diferentes momentos da sua marca.</h2></div><p>Do primeiro clique ao relacionamento contínuo, nossos serviços se complementam para construir uma presença digital forte, consistente e que gera oportunidades.</p></div><div class="services-overview" aria-label="Serviços da JG">${services.map((s,i) => `<article class="overview-service"><span class="icon-box">${icon(servicePages[s.slug].icon)}</span><span class="hub-card-number">0${i+1}</span><h2>${s.name}</h2><p>${s.description}</p><a class="text-link" href="/servicos/${s.slug}/" aria-label="Conhecer serviço: ${s.name}">Conhecer serviço →</a></article>`).join('')}</div></section>
<section class="hub-process"><div class="container hub-process-grid"><div><p class="eyebrow">COMO PENSAMOS CADA SOLUÇÃO</p><h2>Do planejamento<br>aos resultados reais.</h2><p>Seguimos um processo claro e estratégico para entender o cenário, definir o melhor caminho e executar com foco nos seus objetivos.</p></div><ol>${steps.map(([title,text],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><p>${text}</p></li>`).join('')}</ol></div></section>
<section class="container hub-approach" id="nossa-abordagem"><div><p class="eyebrow">NOSSA ABORDAGEM</p><h2>Cada serviço existe<br>para cumprir um objetivo.</h2><p>Unimos estratégia, criatividade e dados para entregar soluções que fazem sentido para o seu momento e para o futuro da sua marca.</p></div><article>${icon('target')}<h3>Estratégia personalizada</h3><p>Cada projeto parte dos objetivos e da realidade do seu negócio.</p></article><article>${icon('chat')}<h3>Comunicação clara</h3><p>Escopo e etapas alinhados, com espaço para você participar das decisões.</p></article><article>${icon('chart')}<h3>Foco em resultado</h3><p>Entregas conectadas ao seu objetivo e aprendizado para orientar a evolução.</p></article></section>
<section class="hub-cta"><div class="container"><div><p class="eyebrow">VAMOS CONVERSAR?</p><h2>Vamos encontrar a solução certa<br>para o seu negócio?</h2></div><p>Conte sobre seu momento e seus objetivos. Vamos pensar nos melhores caminhos para a sua marca crescer com direção.</p><a class="button button-light" href="/contato/">Fale com a gente →</a></div></section></div>`;
}
export function servicePage(service) {
  const profile = servicePages[service.slug];
  const project = service.slug === 'sites' ? `<section class="service-project"><div class="container"><div><p class="eyebrow">PROJETO EM DESTAQUE</p><h2>Fábio Lima Noivos</h2><p>Desenvolvimento de Site</p><p class="project-pending">Imagens e detalhes do projeto aguardam informações reais.</p><a class="button" href="/projetos/fabio-lima-noivos/">Ver case completo</a></div><div>${projectImage()}</div></div></section>` : '';
  return `<div class="service-page service-${profile.theme}">${serviceHero(service, profile)}${includedSection(profile)}${processSection(profile)}${audienceSection(profile)}${project}${serviceFinal(service, profile)}</div>`;
}
