import { navigation, services, contact } from '../data/site.mjs';
export const brand = '<span class="brand-mark">JG<span class="brand-dot">.</span></span><span class="brand-name">AGÊNCIA</span>';
export function header(path) {
  return `<a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="header"><div class="container header-inner"><a class="brand" href="/" aria-label="JG Agência — Início">${brand}</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="menu-principal" aria-label="Abrir menu"><span></span><span></span></button><nav id="menu-principal" class="navigation" aria-label="Navegação principal">${navigation.map(([label, href]) => `<a href="${href}" ${path === href || (href !== '/' && path.startsWith(href)) ? 'aria-current="page"' : ''}>${label}</a>`).join('')}<a class="button button-small header-cta" href="/contato/">Fale com a gente</a></nav></div></header>`;
}
export function footer() {
  return `<footer class="footer"><div class="container footer-grid"><div><a class="brand" href="/" aria-label="JG Agência — Início">${brand}</a><p>Estratégia e presença digital.<br>O próximo passo do seu negócio.</p></div><div><h2>Explore</h2>${navigation.map(([label, href]) => `<a href="${href}">${label}</a>`).join('')}</div><div><h2>Serviços</h2>${services.map(s => `<a href="/servicos/${s.slug}/">${s.name}</a>`).join('')}</div><div><h2>Conecte-se</h2><a href="${contact.instagram}" target="_blank" rel="noopener noreferrer">Instagram<small>${contact.handle}</small></a><a href="${contact.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp<small>${contact.phone}</small></a><a class="email-link" href="mailto:${contact.email}">E-mail<small>${contact.email}</small></a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} JG Agência</span><span>Presença com propósito.</span></div></footer>`;
}
export function document(page, content) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${page.title}</title><meta name="description" content="${page.description}"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="JG Agência"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles/main.css"><link rel="stylesheet" href="/styles/pages.css"><link rel="stylesheet" href="/styles/brand.css">${page.path.startsWith('/servicos/') ? '<link rel="stylesheet" href="/styles/services.css">' : ''}${['/sobre/','/servicos/','/projetos/','/contato/'].includes(page.path) || page.path.startsWith('/projetos/') ? '<link rel="stylesheet" href="/styles/institutional.css">' : ''}<script src="/scripts/navigation.js" defer></script>${(page.path === '/contato/' || page.path === '/') ? '<script src="/scripts/contact.js" type="module"></script>' : ''}</head><body class="${page.path === '/' ? 'home-page' : page.path.startsWith('/servicos/') && page.path !== '/servicos/' ? 'inner-page service-detail-page' : 'inner-page institutional-page'}">${header(page.path)}<main id="conteudo" tabindex="-1">${content}</main>${footer()}</body></html>`;
}
